package main

import "testing"

func Test_ORAS_demo(t *testing.T) {
	ORAS_demo()
}

func Test_RegClient_demo(t *testing.T) {
	certificate := `-----BEGIN CERTIFICATE-----
MIIDPzCCAiegAwIBAgICAJcwDQYJKoZIhvcNAQELBQAwTjELMAkGA1UEBhMCVVMx
CzAJBgNVBAgTAldBMRAwDgYDVQQHEwdTZWF0dGxlMQ8wDQYDVQQKEwZOb3Rhcnkx
DzANBgNVBAMTBnJlZ2N0bDAeFw0yMzAzMjIxNDM3MTJaFw0yMzAzMjMxNDM3MTJa
ME4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEQMA4GA1UEBxMHU2VhdHRsZTEP
MA0GA1UEChMGTm90YXJ5MQ8wDQYDVQQDEwZyZWdjdGwwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCfSfrZG3AJEl1MC4no0j+LVB/ieAM+bqyYdNVUyjUQ
+L/Ic8kf97ZvhBBF59+o3WFMrIcv4Fw2LpBILntXCgKdGBcotI9XcUkj0OiDxyvD
BD5v7kzCKml9KCQd+B/UlYXV3UIebeCxaBMdH1rYhYNFOq3KfLuo0o1CL+kN83l7
SbARVuOkNV5AC93rHAMDvraYh78QOl2SLDZU0k7wVE4I9ZEmUZl/tfEOS3jxswfO
9jxGhFga/PJlfzXwxY4qczRblBlRioy0f+j3J6S9cOL2N3TzI+VRuwT60XXp/ba6
887oi1gMFvSJ83nKweHQvwaoY5y1XzAsj3azk2guw+whAgMBAAGjJzAlMA4GA1Ud
DwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzANBgkqhkiG9w0BAQsFAAOC
AQEAL2UL4JX9f8HwOh0XeHTmfvyCG2QTOCQNv08e+NchV+vywjEBNjQQfIARPw1j
k4NGG4L5qLgSAkPCct1a7CogW/x2czNYh2HubbTIyDKKPp5EDhhnMNQlefr89l89
0qUEZntr71iV+Vi9EZoBUluLKrc79AFb3rgry0QexrlHGuGBWlYRYDu+Vx1ubAgu
vz3uTutPH7aF+v0u/d+bOmWfBwrPjzHyMDhStc9JixCyb1skaNz7TfclqKuyqchQ
/TjaEBw5apiiOjetk0znAjNR+GHoFNXcOyM0qHqThVlra2CBUV0Bp9GomA+Wq12B
tKA5E1/hgkuotISKBOiwtKr28w==
-----END CERTIFICATE-----
`

	repo_name := "localhost:5000/lachie/net-monitor:v1"

	artifact_type := "application/vnd.cyclonedx+json"
	RegClient_Demo(repo_name, certificate, artifact_type)
}
